### ISSUE TITLE
Conversion de archivo Excel a json

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_mid#1]
se requiere de una conversion de un archivo de Microsoft Excel (*.xlsx) a una respuesta Json con los elementos de las facturas asociadas al acta de recibido

- [x] Captura del Archivo

- [x] Lectura de elementos

- [x] Respuesta JSON

**Comment by ManuelMurillo** [comment]
falta definir en una reunion las caracteristicas especificas de la carga para poder establecer las pautas de lectura en el codigo, sin embargo se genera una prueba exitosa con el siguiente archivo de referencia
https://drive.google.com/open?id=1MmkxC4tVFxPrIEtraLTXHkybYxnnCm4urhXdGOiJ1D4

**Comment by mafeave** [comment]
Se verifica funcionalidad de cargue de archivo (*.xlsx) a JSON.
NOTA: definir  las caracteristicas especificas de la carga para poder establecer las pautas de lectura en el codigo, así como los posibles tipos de archivos.
