### ISSUE TITLE
Reflejar Entrada en su movimiento contable

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_mid#115]
Con base a [lo expuesto](https://github.com/udistrital/arka_cliente/issues/540#issuecomment-791603935), hay que modificar el controlador de registro de entradas para que no solamente modifique las APIS CRUD asociadas a Arka, sino que también realice el movimiento contable respectivo

- [x] Traer las cuentas contables de cada clase de cada elemento: Identificar en el POST enviado del Cliente al MID; si las cuentas contables ya vienen o si al menos viene información suficiente que permita averiguarlas indirectamente, haciendo un query al CRUD catálogo desde el mismo MID.
- [x] Con las cuentas anteriores, probar el funcionamiento del [MID de Movimientos contables](https://github.com/udistrital/movimientos_contables_mid), registrando un movimiento contable para una entrada de prueba, de acuerdo a [lo explicado](https://drive.google.com/file/d/1Ts-fQO38urNLym_lN351IdVb0Uga7T8H/view). Se recomienda crear una única transacción con todos los movimientos implicados (y así crear una transacción desglosada, que afecta a más de dos cuentas de ser necesario)
- [x] Integrar lo anterior

Entrega estimada: 07/13/21

**Comment by AlexFBP** [comment]
Revisar si esto tiene que ver con
- udistrital/arka_mid#27
- (de la anterior) udistrital/catalogo_elementos_crud#11

**Comment by AlexFBP** [comment]
Tener en cuenta en el desarrollo lo mencionado en la mesa del 27/07/21: Todos los elementos deben tener asociadas cuentas contables válidas antes de poder realizar el movimiento

**Comment by juandavidvelezaalvarez** [comment]
Los commit de este pull request de septiembre 20 al 27 están asociados a esta actividad https://github.com/udistrital/arka_mid/pull/174

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial y comportamiento actual del sistema
