### ISSUE TITLE
Parametros para registro, edicion y verificacion de actas

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_mid#2]
se requiere a travez del mid traer los datos asociados a parametros de consulta para poder generar registros de actas de recibido con:

- [x] Proveedores

- [x] IVA

- [x] Unidades

- [x] Sedes

- [x] Ubicaciones

- [x] Parametros de acta CRUD

**Comment by ManuelMurillo** [comment]
Repositorios Asociados

- [ ] https://github.com/udistrital/arka_cliente/issues/91

- [ ] https://github.com/udistrital/arka_cliente/issues/86

- [ ] https://github.com/udistrital/arka_cliente/issues/85

- [ ] https://github.com/udistrital/arka_cliente/issues/72

**Comment by mafeave** [comment]
Se verifican los ajustes realizados.
