### ISSUE TITLE
 Ajustar consulta de entrada con la afectación de cuentas contables

### ISSUE THREAD

**Issue by anndresfelipe29** [udistrital/arka_mid#27]
Ajustar consulta de entrada con la afectación de cuentas contables

**Comment by anndresfelipe29** [comment]
Se realiza la consulta a partir de un arreglo de subgrupos, se verifica si es hijo o padre, en caso de ser hijo se recorre el árbol en busca de su padre, encontrando los datos de la tabla cuentas_subgrupo asociados.

**Comment by anndresfelipe29** [comment]
https://github.com/udistrital/arka_mid/commit/6823ef845330f6d3363d04a213ca75a37f1f37e2

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial.
Lo que quedó pendiente (mencionado arriba) se-continuará-en/hace-parte-de udistrital/catalogo_elementos_crud#11
