### ISSUE TITLE
Consulta de datos para apertura de Kardex

### ISSUE THREAD

**Issue by anndresfelipe29** [udistrital/arka_mid#34]
A causa de lo siguiente no se pudo realizar la consulta:
- No hay una relación entre un elemento genérico y uno real, el primero esta en el esquema de catalogo y el segundo en el esquema de movimientos. Por lo tanto, no se puede hacer la consulta a partir de un elemento genérico del catalogo.
- Es confuso encontrar el historial del elemento, dado que, los elementos relacionados a un movimiento tipo entrada están registrados en la tabla de elementos acta de recibido. Mientras que los elementos asociados a un movimiento tipo salida se encuentran en la tabla de elementos de movimientos.
- Para poder hacer un kardex de un elemento en el catalogo se debe asociar tres esquemas diferentes para obtener la información completa de un solo elemento. Donde relacionar un elemento del esquema catalogo con cualquiera de los otros dos actualmente no es posible.

Se recomienda estudiar la posibilidad de ver los elementos como un esquema independiente o tener una única tabla de elemento para poder generar el historial de cada elemento registrado.

**Comment by ManuelMurillo** [comment]
Teniendo en cuenta la reunion del 13 de enero, se realizaron los ajustes de API en el issue relacionado

https://github.com/udistrital/arka_cliente/issues/256

En el siguiente issue se propone el desarrollo de la apertura de kardex:

https://github.com/udistrital/arka_cliente/issues/255

la consulta del kardex se propone de la siguiente forma:
![image](https://user-images.githubusercontent.com/29108085/72745033-cbd5ee80-3b7c-11ea-890a-8a6c20192145.png)

y se proponen las siguientes tareas para completar los los movimientos del kardex:

- [ ] Consulta General de Kardex: Donde se tomaran los registros relacionados dependiendo del tipo de Formato (Apertura de Kardex)

- [ ] Consulta Especifica: donde se listaran los elementos especificos asociados al elemento delacionado del catalogo teniendo en cuenta los movimientos de forma cronologica o heredada de un movimiento anterior

- [ ] Transaccion de Kardex:realizar una transaccion Independiente del movimiento a realizar(Apertura, Entrada, Salida)

- [ ] Ajuste de componente Kardex(Cliente)
