### ISSUE TITLE
Crear función para ajustar los datos necesario para cargar el input de la asignación de cuantas contables 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_mid#50]
Se debe realizar una función a nivel de api crud de kronos para crear el controlador que retorne los datos necesario para consumir las cuentas contables en nuestro cliente, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar el controlador que retorne la data necesaria para las cuenta contables 

- [x] Consumir la función en el cliente

**Comment by CristianDavidSanchez** [comment]
Se genera la función que toma la data de kronos con la estructura necesaria y filtrada por la naturaleza de cuenta, por ahora de manera local.
![Opera Captura de pantalla_2020-11-30_201959_localhost](https://user-images.githubusercontent.com/45292213/100684989-72684f80-3349-11eb-9ed2-44d1e5d1ab3b.png)

**Comment by fabianbarreto02** [comment]
Se revisa las issue
