### ISSUE TITLE
Ajustar método get all actas para recibir parámetro query y consultar un estado del acta especifico

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_mid#53]
Se debe ajustar el metodo de get all actas para que pueda recibir un parametro de consulta y este responda solo las actas con el estado requerido, la issue debe cumplir con las siguientes requerimientos:

- [x] Ajustar el método para que reciba el parámetro y este devuelva las actas con el estado requerido

**Comment by AlexFBP** [comment]
Se empieza a abordar el *Issue*

**Comment by AlexFBP** [comment]
Se crea el parámetro GET `states`, al cual se le asigna una lista de estados, separados por comas. Adicionalmente se actualizó la documentación a ser reflejada en swagger:

![image](https://user-images.githubusercontent.com/6588872/103603256-2d9d7e80-4edc-11eb-886b-64923b4bfee3.png)

Hay un tráfico de red innecesario que impacta en el rendimiento de esta petición, y podría mejorar bastante si las siguientes tareas que se realizan en el MID, se movieran al CRUD:
- Internamente trae TODOS los históricos de TODAS las actas y selecciona la más reciente
- Al resultado anterior, en caso de haberse especificado `states`, se filtran las actas con alguno de estos estados

Actualmente, y corriendo esta API bajo VPN, se demora 3~4 segundos, con 16 actas y ~80 registros de `historico_acta`
