### ISSUE TITLE
Realizar funcionalida para consulta de supervisores con su respectiva sede 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_mid#92]
Se debe realizar la función que permita la consulta de los terceros que tienen el cargo de supervisores en el api de terceros en tabla de vinculaciones y con su respectivo dependencia que se debe consultar en el api de oikos, se debe ajustar  las consultas que se realicen en el modulo de entradas con los tipos de entradas definidos, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar la función a nivel de mid para la consulta de todos los terceros con los supervisores y realizar la consulta de la dependencia asociado al tercero en el api de oikos
- [x] Ajustar las consultas en el modulo de entradas que requiera ese ajuste realizado

**Comment by AlexFBP** [comment]
Prerrequisito para udistrital/arka_cliente#432
Posiblemente es el mismo PR #95

**Comment by AlexFBP** [comment]
Para el segundo item, los ajustes se realizaron en udistrital/arka_cliente#495

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
